# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wallet
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  pod 'MessageKit'
  pod 'JGProgressHUD'
  pod 'RealmSwift'
  pod 'SDWebImage'
  pod 'SnapKit'
  pod 'Then'
end
